### ISSUE TITLE
MATI Flow no different webhook url

### ISSUE THREAD

**Issue by matrixn** [GetMati/mati-web-button#11]
Hi all, 

when using mati flows, i was expecting to be able to see different webhook url for each flow i set up but apparently when i change the webhook in each flow, i get same webhook in all flows which makes the flow system kinda useless....

Question is, is this a bug or that's how it was designed to work which is useless unless the flow only changes the customization only....?

Thanks

**Comment by dkchv** [comment]
we released such feature to split flows and webhooks. please, setup nee ones on your dashboard/flow page
